name = "workers"
main = "index.js"
compatibility_date = "2026-08-26"
[observability]
enabled = false
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
